export type LangCode =
  | "id" | "en" | "ms" | "fil" | "ja" | "zh" | "ko" | "th" | "es" | "de" | "fr";

export interface Language {
  code: LangCode;
  label: string;
  flag: string;
  dir: "ltr" | "rtl";
}

export const LANGUAGES: Language[] = [
  { code: "id", label: "Indonesia", flag: "🇮🇩", dir: "ltr" },
  { code: "en", label: "English", flag: "🇬🇧", dir: "ltr" },
  { code: "ms", label: "Melayu", flag: "🇲🇾", dir: "ltr" },
  { code: "fil", label: "Filipino", flag: "🇵🇭", dir: "ltr" },
  { code: "ja", label: "日本語", flag: "🇯🇵", dir: "ltr" },
  { code: "zh", label: "中文", flag: "🇨🇳", dir: "ltr" },
  { code: "ko", label: "한국어", flag: "🇰🇷", dir: "ltr" },
  { code: "th", label: "ภาษาไทย", flag: "🇹🇭", dir: "ltr" },
  { code: "es", label: "Español", flag: "🇪🇸", dir: "ltr" },
  { code: "de", label: "Deutsch", flag: "🇩🇪", dir: "ltr" },
  { code: "fr", label: "Français", flag: "🇫🇷", dir: "ltr" },
];

export const BOOK_LIST = [
  { key: "all", id: "Semua Kitab", en: "All Books", ms: "Semua Kitab", fil: "Lahat ng Aklat", ja: "全書", zh: "全部", ko: "전체", th: "ทั้งหมด", es: "Todos", de: "Alle", fr: "Tous" },
  { key: "bukhari", id: "Shahih Bukhari", en: "Sahih Bukhari", ms: "Sahih Bukhari", fil: "Sahih Bukhari", ja: "ブハーリー", zh: "布哈里圣训", ko: "부카리", th: "บุคอรี", es: "Sahih Bujari", de: "Sahih Bukhari", fr: "Sahih Boukhari" },
  { key: "muslim", id: "Shahih Muslim", en: "Sahih Muslim", ms: "Sahih Muslim", fil: "Sahih Muslim", ja: "ムスリム", zh: "穆斯林圣训", ko: "무슬림", th: "มุสลิม", es: "Sahih Muslim", de: "Sahih Muslim", fr: "Sahih Muslim" },
  { key: "abudawud", id: "Sunan Abu Dawud", en: "Sunan Abu Dawud", ms: "Sunan Abu Dawud", fil: "Sunan Abu Dawud", ja: "アブー・ダーウード", zh: "艾布达伍德圣训", ko: "아부다우드", th: "อบูดาวูด", es: "Sunan Abu Dawud", de: "Sunan Abu Dawud", fr: "Sunan Abou Dawoud" },
  { key: "tirmidhi", id: "Sunan Tirmidzi", en: "Sunan Tirmidhi", ms: "Sunan Tirmizi", fil: "Sunan Tirmidhi", ja: "ティルミズィー", zh: "提尔米齐圣训", ko: "티르미디", th: "ติรมีซี", es: "Sunan Tirmidhi", de: "Sunan Tirmidhi", fr: "Sunan Tirmidhi" },
  { key: "nasai", id: "Sunan An-Nasa'i", en: "Sunan An-Nasa'i", ms: "Sunan An-Nasai", fil: "Sunan An-Nasa'i", ja: "ナサーイー", zh: "纳萨伊圣训", ko: "나사이", th: "นะซาอี", es: "Sunan An-Nasa'i", de: "Sunan An-Nasa'i", fr: "Sunan An-Nasa'i" },
  { key: "ibnmajah", id: "Sunan Ibnu Majah", en: "Sunan Ibn Majah", ms: "Sunan Ibn Majah", fil: "Sunan Ibn Majah", ja: "イブン・マージャ", zh: "伊本马贾圣训", ko: "이븐마자", th: "อิบนุมาญะฮ์", es: "Sunan Ibn Mayah", de: "Sunan Ibn Majah", fr: "Sunan Ibn Majah" },
];

export const UI_TEXT: Record<LangCode, {
  tagline: string;
  subtitle: string;
  placeholder: string;
  searchBtn: string;
  randomBtn: string;
  randomTip: string;
  suggestedTopics: string;
  loading: string;
  noResult: string;
  noResultSub: string;
  foundLabel: (n: number, q: string) => string;
  showFull: string;
  hideFull: string;
  showArabic: string;
  hideArabic: string;
  aiLabel: string;
  lessonLabel: string;
  shareLabel: string;
  copied: string;
  bookmarkAdd: string;
  bookmarkRemove: string;
  bookmarksTitle: string;
  bookmarksEmpty: string;
  filterLabel: string;
  footer: string;
  footerCredit: string;
  donationTitle: string;
  donationDesc: string;
  topics: string[];
}> = {
  id: {
    tagline: "Sunnah in your pocket",
    subtitle: "Temukan hadis Nabi ﷺ berdasarkan tema atau kata kunci, lengkap dengan penjelasan AI",
    placeholder: "Cari hadis... misal: sabar, sholat, rezeki",
    searchBtn: "Cari",
    randomBtn: "Acak",
    randomTip: "Tekan Enter atau klik Cari · 🔀 untuk hadis acak",
    suggestedTopics: "Coba cari topik:",
    loading: "Mencari hadis & menyiapkan penjelasan...",
    noResult: "Tidak ditemukan hadis untuk kata kunci tersebut.",
    noResultSub: "Coba gunakan kata yang lebih umum.",
    foundLabel: (n, q) => `${n} hadis ditemukan untuk "${q}"`,
    showFull: "Lihat hadis lengkap",
    hideFull: "Sembunyikan",
    showArabic: "Lihat teks Arab",
    hideArabic: "Sembunyikan teks Arab",
    aiLabel: "Penjelasan AI",
    lessonLabel: "Pelajaran",
    shareLabel: "Bagikan",
    copied: "Disalin!",
    bookmarkAdd: "Simpan",
    bookmarkRemove: "Hapus simpanan",
    bookmarksTitle: "Hadis Tersimpan",
    bookmarksEmpty: "Belum ada hadis yang disimpan.",
    filterLabel: "Filter kitab",
    footer: "Sumber: fawazahmed0/hadith-api · Penjelasan: Groq AI · Semoga bermanfaat 🤲",
    footerCredit: "Dibuat dengan ❤️ untuk umat",
    donationTitle: "Dukung Sunnafy",
    donationDesc: "Bantu kami terus mengembangkan platform ini",
    topics: ["sabar", "sholat", "rezeki", "jujur", "ikhlas", "sedekah", "taubat", "doa"],
  },
  en: {
    tagline: "Sunnah in your pocket",
    subtitle: "Find hadiths of the Prophet ﷺ by theme or keyword, with AI-powered explanations",
    placeholder: "Search hadith... e.g: patience, prayer, sustenance",
    searchBtn: "Search",
    randomBtn: "Random",
    randomTip: "Press Enter or click Search · 🔀 for a random hadith",
    suggestedTopics: "Try searching:",
    loading: "Searching hadiths & preparing explanations...",
    noResult: "No hadiths found for that keyword.",
    noResultSub: "Try using a more general word.",
    foundLabel: (n, q) => `${n} hadiths found for "${q}"`,
    showFull: "Show full hadith",
    hideFull: "Hide",
    showArabic: "Show Arabic text",
    hideArabic: "Hide Arabic text",
    aiLabel: "AI Explanation",
    lessonLabel: "Lesson",
    shareLabel: "Share",
    copied: "Copied!",
    bookmarkAdd: "Bookmark",
    bookmarkRemove: "Remove bookmark",
    bookmarksTitle: "Saved Hadiths",
    bookmarksEmpty: "No saved hadiths yet.",
    filterLabel: "Filter by book",
    footer: "Source: fawazahmed0/hadith-api · Explanations: Groq AI · May it be beneficial 🤲",
    footerCredit: "Made with ❤️ for the ummah",
    donationTitle: "Support Sunnafy",
    donationDesc: "Help us keep developing this platform",
    topics: ["patience", "prayer", "sustenance", "honesty", "sincerity", "charity", "repentance", "supplication"],
  },
  ms: {
    tagline: "Sunnah in your pocket",
    subtitle: "Cari hadis Nabi ﷺ mengikut tema atau kata kunci, lengkap dengan penjelasan AI",
    placeholder: "Cari hadis... contoh: sabar, solat, rezeki",
    searchBtn: "Cari",
    randomBtn: "Rawak",
    randomTip: "Tekan Enter atau klik Cari · 🔀 untuk hadis rawak",
    suggestedTopics: "Cuba cari topik:",
    loading: "Mencari hadis & menyediakan penjelasan...",
    noResult: "Tiada hadis ditemui untuk kata kunci tersebut.",
    noResultSub: "Cuba gunakan perkataan yang lebih umum.",
    foundLabel: (n, q) => `${n} hadis ditemui untuk "${q}"`,
    showFull: "Lihat hadis penuh",
    hideFull: "Sembunyikan",
    showArabic: "Lihat teks Arab",
    hideArabic: "Sembunyikan teks Arab",
    aiLabel: "Penjelasan AI",
    lessonLabel: "Pengajaran",
    shareLabel: "Kongsi",
    copied: "Disalin!",
    bookmarkAdd: "Simpan",
    bookmarkRemove: "Buang simpanan",
    bookmarksTitle: "Hadis Tersimpan",
    bookmarksEmpty: "Tiada hadis tersimpan lagi.",
    filterLabel: "Tapis kitab",
    footer: "Sumber: fawazahmed0/hadith-api · Penjelasan: Groq AI · Semoga bermanfaat 🤲",
    footerCredit: "Dibuat dengan ❤️ untuk umat",
    donationTitle: "Sokong Sunnafy",
    donationDesc: "Bantu kami terus membangunkan platform ini",
    topics: ["sabar", "solat", "rezeki", "jujur", "ikhlas", "sedekah", "taubat", "doa"],
  },
  fil: {
    tagline: "Sunnah in your pocket",
    subtitle: "Hanapin ang mga hadith ng Propeta ﷺ ayon sa paksa o keyword, na may paliwanag ng AI",
    placeholder: "Maghanap ng hadith... hal: pasensya, dasal, kabuhayan",
    searchBtn: "Hanapin",
    randomBtn: "Random",
    randomTip: "Pindutin ang Enter o i-click ang Hanapin · 🔀 para sa random na hadith",
    suggestedTopics: "Subukang maghanap:",
    loading: "Naghahanap ng mga hadith at naghahanda ng mga paliwanag...",
    noResult: "Walang hadith na natagpuan para sa keyword na iyon.",
    noResultSub: "Subukan ang mas pangkalahatang salita.",
    foundLabel: (n, q) => `${n} hadith na natagpuan para sa "${q}"`,
    showFull: "Ipakita ang buong hadith",
    hideFull: "Itago",
    showArabic: "Ipakita ang tekstong Arabe",
    hideArabic: "Itago ang tekstong Arabe",
    aiLabel: "Paliwanag ng AI",
    lessonLabel: "Aral",
    shareLabel: "Ibahagi",
    copied: "Nakopya!",
    bookmarkAdd: "I-save",
    bookmarkRemove: "Alisin",
    bookmarksTitle: "Mga Na-save na Hadith",
    bookmarksEmpty: "Wala pang na-save na hadith.",
    filterLabel: "I-filter ayon sa aklat",
    footer: "Pinagmulan: fawazahmed0/hadith-api · Paliwanag: Groq AI · Nawa ay mapakinabangan 🤲",
    footerCredit: "Ginawa nang may ❤️ para sa ummah",
    donationTitle: "Suportahan ang Sunnafy",
    donationDesc: "Tulungan kaming patuloy na paunlarin ang platform na ito",
    topics: ["pasensya", "dasal", "kabuhayan", "katapatan", "pagmamahal", "kawanggawa", "pagsisisi", "panalangin"],
  },
  ja: {
    tagline: "Sunnah in your pocket",
    subtitle: "テーマやキーワードで預言者ﷺのハディースを検索し、AIによる解説付き",
    placeholder: "ハディースを検索... 例: 忍耐, 礼拝, 糧",
    searchBtn: "検索",
    randomBtn: "ランダム",
    randomTip: "Enterキーまたは検索ボタンをクリック · 🔀 でランダムなハディース",
    suggestedTopics: "おすすめのトピック:",
    loading: "ハディースを検索中・解説を準備中...",
    noResult: "そのキーワードのハディースは見つかりませんでした。",
    noResultSub: "より一般的な言葉を試してください。",
    foundLabel: (n, q) => `「${q}」で${n}件のハディースが見つかりました`,
    showFull: "ハディース全文を表示",
    hideFull: "非表示",
    showArabic: "アラビア語テキストを表示",
    hideArabic: "アラビア語テキストを非表示",
    aiLabel: "AIによる解説",
    lessonLabel: "教訓",
    shareLabel: "共有",
    copied: "コピーしました！",
    bookmarkAdd: "保存",
    bookmarkRemove: "削除",
    bookmarksTitle: "保存済みハディース",
    bookmarksEmpty: "保存されたハディースはまだありません。",
    filterLabel: "書籍でフィルター",
    footer: "出典: fawazahmed0/hadith-api · 解説: Groq AI · お役に立てれば幸いです 🤲",
    footerCredit: "ウンマのために❤️で作られました",
    donationTitle: "Sunnafyをサポート",
    donationDesc: "このプラットフォームの開発を続けるためにご支援ください",
    topics: ["忍耐", "礼拝", "糧", "誠実", "誠意", "慈善", "悔悛", "祈り"],
  },
  zh: {
    tagline: "Sunnah in your pocket",
    subtitle: "按主题或关键词搜索先知ﷺ的圣训，附AI解释",
    placeholder: "搜索圣训... 例如: 忍耐, 礼拜, 生计",
    searchBtn: "搜索",
    randomBtn: "随机",
    randomTip: "按Enter或点击搜索 · 🔀 随机圣训",
    suggestedTopics: "尝试搜索:",
    loading: "正在搜索圣训并准备解释...",
    noResult: "未找到该关键词的圣训。",
    noResultSub: "请尝试使用更常见的词语。",
    foundLabel: (n, q) => `找到"${q}"相关的${n}条圣训`,
    showFull: "显示完整圣训",
    hideFull: "隐藏",
    showArabic: "显示阿拉伯文",
    hideArabic: "隐藏阿拉伯文",
    aiLabel: "AI解释",
    lessonLabel: "启示",
    shareLabel: "分享",
    copied: "已复制！",
    bookmarkAdd: "收藏",
    bookmarkRemove: "取消收藏",
    bookmarksTitle: "已收藏圣训",
    bookmarksEmpty: "暂无收藏的圣训。",
    filterLabel: "按书籍筛选",
    footer: "来源: fawazahmed0/hadith-api · 解释: Groq AI · 愿有所裨益 🤲",
    footerCredit: "用❤️为乌玛制作",
    donationTitle: "支持Sunnafy",
    donationDesc: "帮助我们继续开发这个平台",
    topics: ["忍耐", "礼拜", "生计", "诚实", "虔诚", "慈善", "悔罪", "祈祷"],
  },
  ko: {
    tagline: "Sunnah in your pocket",
    subtitle: "테마나 키워드로 예언자ﷺ의 하디스를 검색하고 AI 해설을 확인하세요",
    placeholder: "하디스 검색... 예: 인내, 기도, 생계",
    searchBtn: "검색",
    randomBtn: "랜덤",
    randomTip: "Enter를 누르거나 검색을 클릭 · 🔀 랜덤 하디스",
    suggestedTopics: "추천 주제:",
    loading: "하디스 검색 및 해설 준비 중...",
    noResult: "해당 키워드의 하디스를 찾을 수 없습니다.",
    noResultSub: "더 일반적인 단어를 사용해 보세요.",
    foundLabel: (n, q) => `"${q}"에 대한 하디스 ${n}개 발견`,
    showFull: "전체 하디스 보기",
    hideFull: "숨기기",
    showArabic: "아랍어 텍스트 보기",
    hideArabic: "아랍어 텍스트 숨기기",
    aiLabel: "AI 해설",
    lessonLabel: "교훈",
    shareLabel: "공유",
    copied: "복사됨!",
    bookmarkAdd: "저장",
    bookmarkRemove: "삭제",
    bookmarksTitle: "저장된 하디스",
    bookmarksEmpty: "저장된 하디스가 없습니다.",
    filterLabel: "책으로 필터",
    footer: "출처: fawazahmed0/hadith-api · 해설: Groq AI · 도움이 되길 바랍니다 🤲",
    footerCredit: "움마를 위해 ❤️로 만들었습니다",
    donationTitle: "Sunnafy 지원하기",
    donationDesc: "이 플랫폼을 계속 개발할 수 있도록 도와주세요",
    topics: ["인내", "기도", "생계", "정직", "성실", "자선", "회개", "간구"],
  },
  th: {
    tagline: "Sunnah in your pocket",
    subtitle: "ค้นหาหะดีษของท่านนบีﷺ ตามหัวข้อหรือคำสำคัญ พร้อมคำอธิบายจาก AI",
    placeholder: "ค้นหาหะดีษ... เช่น: อดทน, ละหมาด, ริซกี",
    searchBtn: "ค้นหา",
    randomBtn: "สุ่ม",
    randomTip: "กด Enter หรือคลิกค้นหา · 🔀 สำหรับหะดีษแบบสุ่ม",
    suggestedTopics: "ลองค้นหาหัวข้อ:",
    loading: "กำลังค้นหาหะดีษและเตรียมคำอธิบาย...",
    noResult: "ไม่พบหะดีษสำหรับคำค้นหานั้น",
    noResultSub: "ลองใช้คำที่ทั่วไปกว่านี้",
    foundLabel: (n, q) => `พบหะดีษ ${n} รายการสำหรับ "${q}"`,
    showFull: "แสดงหะดีษทั้งหมด",
    hideFull: "ซ่อน",
    showArabic: "แสดงข้อความภาษาอาหรับ",
    hideArabic: "ซ่อนข้อความภาษาอาหรับ",
    aiLabel: "คำอธิบาย AI",
    lessonLabel: "บทเรียน",
    shareLabel: "แชร์",
    copied: "คัดลอกแล้ว!",
    bookmarkAdd: "บันทึก",
    bookmarkRemove: "ลบ",
    bookmarksTitle: "หะดีษที่บันทึกไว้",
    bookmarksEmpty: "ยังไม่มีหะดีษที่บันทึกไว้",
    filterLabel: "กรองตามหนังสือ",
    footer: "แหล่งที่มา: fawazahmed0/hadith-api · คำอธิบาย: Groq AI · หวังว่าจะเป็นประโยชน์ 🤲",
    footerCredit: "สร้างด้วย ❤️ เพื่ออุมมะฮ์",
    donationTitle: "สนับสนุน Sunnafy",
    donationDesc: "ช่วยเราพัฒนาแพลตฟอร์มนี้ต่อไป",
    topics: ["อดทน", "ละหมาด", "ริซกี", "ซื่อสัตย์", "บริสุทธิ์ใจ", "ทาน", "เตาบะฮ์", "ดุอา"],
  },
  es: {
    tagline: "Sunnah in your pocket",
    subtitle: "Encuentra hadices del Profeta ﷺ por tema o palabra clave, con explicaciones de IA",
    placeholder: "Buscar hadiz... ej: paciencia, oración, sustento",
    searchBtn: "Buscar",
    randomBtn: "Aleatorio",
    randomTip: "Presiona Enter o haz clic en Buscar · 🔀 para un hadiz aleatorio",
    suggestedTopics: "Prueba buscar:",
    loading: "Buscando hadices y preparando explicaciones...",
    noResult: "No se encontraron hadices para esa palabra clave.",
    noResultSub: "Intenta usar una palabra más general.",
    foundLabel: (n, q) => `${n} hadices encontrados para "${q}"`,
    showFull: "Ver hadiz completo",
    hideFull: "Ocultar",
    showArabic: "Mostrar texto árabe",
    hideArabic: "Ocultar texto árabe",
    aiLabel: "Explicación de IA",
    lessonLabel: "Lección",
    shareLabel: "Compartir",
    copied: "¡Copiado!",
    bookmarkAdd: "Guardar",
    bookmarkRemove: "Eliminar",
    bookmarksTitle: "Hadices Guardados",
    bookmarksEmpty: "No hay hadices guardados aún.",
    filterLabel: "Filtrar por libro",
    footer: "Fuente: fawazahmed0/hadith-api · Explicaciones: Groq AI · Que sea de beneficio 🤲",
    footerCredit: "Hecho con ❤️ para la ummah",
    donationTitle: "Apoyar Sunnafy",
    donationDesc: "Ayúdanos a seguir desarrollando esta plataforma",
    topics: ["paciencia", "oración", "sustento", "honestidad", "sinceridad", "caridad", "arrepentimiento", "súplica"],
  },
  de: {
    tagline: "Sunnah in your pocket",
    subtitle: "Finde Hadithe des Propheten ﷺ nach Thema oder Stichwort, mit KI-Erklärungen",
    placeholder: "Hadith suchen... z.B: Geduld, Gebet, Lebensunterhalt",
    searchBtn: "Suchen",
    randomBtn: "Zufällig",
    randomTip: "Enter drücken oder Suchen klicken · 🔀 für zufälligen Hadith",
    suggestedTopics: "Themen ausprobieren:",
    loading: "Hadithe werden gesucht und Erklärungen vorbereitet...",
    noResult: "Keine Hadithe für dieses Stichwort gefunden.",
    noResultSub: "Versuche ein allgemeineres Wort.",
    foundLabel: (n, q) => `${n} Hadithe gefunden für „${q}"`,
    showFull: "Vollständigen Hadith anzeigen",
    hideFull: "Ausblenden",
    showArabic: "Arabischen Text anzeigen",
    hideArabic: "Arabischen Text ausblenden",
    aiLabel: "KI-Erklärung",
    lessonLabel: "Lektion",
    shareLabel: "Teilen",
    copied: "Kopiert!",
    bookmarkAdd: "Speichern",
    bookmarkRemove: "Entfernen",
    bookmarksTitle: "Gespeicherte Hadithe",
    bookmarksEmpty: "Noch keine gespeicherten Hadithe.",
    filterLabel: "Nach Buch filtern",
    footer: "Quelle: fawazahmed0/hadith-api · Erklärungen: Groq AI · Möge es nützlich sein 🤲",
    footerCredit: "Mit ❤️ für die Ummah gemacht",
    donationTitle: "Sunnafy unterstützen",
    donationDesc: "Hilf uns, diese Plattform weiterzuentwickeln",
    topics: ["Geduld", "Gebet", "Lebensunterhalt", "Ehrlichkeit", "Aufrichtigkeit", "Wohltätigkeit", "Reue", "Bittgebet"],
  },
  fr: {
    tagline: "Sunnah in your pocket",
    subtitle: "Trouvez les hadiths du Prophète ﷺ par thème ou mot-clé, avec des explications IA",
    placeholder: "Rechercher un hadith... ex: patience, prière, subsistance",
    searchBtn: "Rechercher",
    randomBtn: "Aléatoire",
    randomTip: "Appuyez sur Entrée ou cliquez sur Rechercher · 🔀 pour un hadith aléatoire",
    suggestedTopics: "Essayez de rechercher:",
    loading: "Recherche de hadiths et préparation des explications...",
    noResult: "Aucun hadith trouvé pour ce mot-clé.",
    noResultSub: "Essayez d'utiliser un mot plus général.",
    foundLabel: (n, q) => `${n} hadiths trouvés pour « ${q} »`,
    showFull: "Voir le hadith complet",
    hideFull: "Masquer",
    showArabic: "Afficher le texte arabe",
    hideArabic: "Masquer le texte arabe",
    aiLabel: "Explication IA",
    lessonLabel: "Leçon",
    shareLabel: "Partager",
    copied: "Copié !",
    bookmarkAdd: "Enregistrer",
    bookmarkRemove: "Supprimer",
    bookmarksTitle: "Hadiths Enregistrés",
    bookmarksEmpty: "Aucun hadith enregistré pour l'instant.",
    filterLabel: "Filtrer par livre",
    footer: "Source: fawazahmed0/hadith-api · Explications: Groq AI · Puisse-t-il être bénéfique 🤲",
    footerCredit: "Fait avec ❤️ pour la oummah",
    donationTitle: "Soutenir Sunnafy",
    donationDesc: "Aidez-nous à continuer à développer cette plateforme",
    topics: ["patience", "prière", "subsistance", "honnêteté", "sincérité", "charité", "repentir", "supplication"],
  },
};
